#!/usr/bin/python
#coding=utf-8

def fibonacci(n):
    current, next = 1, 2
    for i in xrange(1, n):
        current, next = next, current + next
    return current

def answer(max):
    '''
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    '''
    sum = 0
    i = 1
    while ( fibonacci(i) <= max ):
        fi = fibonacci(i)
        if fi % 2 == 0:
            sum += fi
        i += 1
    return sum

if __name__ == '__main__':
    print answer(4000000)
